# 1. UPSTREAM (server backend)
upstream backend_upstream {
    server backend:5050;
}

upstream socket_upstream {
    ip_hash;
    server socket:5070;
}

upstream ai_upstream {
    server ai-python:8080;
}

# 2. HTTP -> HTTPS REDIRECT
server {
    listen 80;
    server_name hustvanvo.io.vn 
                www.hustvanvo.io.vn 
                ai.hustvanvo.io.vn 
                api.hustvanvo.io.vn 
                socket.hustvanvo.io.vn;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
    
}

# 3. FRONTEND (Main Domain)
server {
    listen 443 ssl;
    server_name hustvanvo.io.vn www.hustvanvo.io.vn;
    server_tokens off;

    # SSL Config
    ssl_certificate /etc/letsencrypt/live/hustvanvo.io.vn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hustvanvo.io.vn/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Frontend Static Files
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Cache static file
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}

# 4. BACKEND API
server {
    listen 443 ssl;
    server_name api.hustvanvo.io.vn;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/hustvanvo.io.vn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hustvanvo.io.vn/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://backend_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_connect_timeout 2s;
    }
}

# 5. SOCKET SERVICE
server {
    listen 443 ssl;
    server_name socket.hustvanvo.io.vn;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/hustvanvo.io.vn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hustvanvo.io.vn/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://socket_upstream;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_connect_timeout 2s;
    }
}

# 6. AI PYTHON SERVICE
server {
    listen 443 ssl;
    server_name ai.hustvanvo.io.vn;

    ssl_certificate /etc/letsencrypt/live/hustvanvo.io.vn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hustvanvo.io.vn/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 50M;
    proxy_read_timeout 300s;
    proxy_connect_timeout 300s;

    location / {
        proxy_pass http://ai_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_connect_timeout 2s;
    }
}